#cloud-config
package_update: true
package_upgrade: true

# packages:
#   - openjdk-17-jdk
#   - unzip

# runcmd:
#   - adduser --system --no-create-home sonarqube
#   - cd /opt
#   - wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.0.65466.zip
#   - unzip sonarqube-9.9.0.65466.zip
#   - mv sonarqube-9.9.0.65466 sonarqube
#   - chown -R sonarqube:sonarqube /opt/sonarqube
#   - |
#     echo '[Unit]
#     Description=SonarQube service
#     After=syslog.target network.target

#     [Service]
#     Type=forking
#     ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
#     ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
#     User=sonarqube
#     Group=sonarqube
#     Restart=always

#     [Install]
#     WantedBy=multi-user.target' > /etc/systemd/system/sonarqube.service
#   - systemctl daemon-reload
#   - systemctl start sonarqube
#   - systemctl enable sonarqube